version: 2.1
jobs:
  merge:
    name: Merge repo
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: MikuX-Dev/gpt4
          token: ${{ secrets.PAT_TOKEN }}
      - name: Configure Git
        run: |
          git config user.name "MikuX-Dev"
          git config user.email "abinishanth3464@gmail.com"
      - name: Clone gpt4
        run: git clone https://github.com/xtekky/gpt4free.git
      - name: Add my repo
        run: git remote add second-repo git@github.com:MikuX-Dev/gpt4.git
      - name: Fetch my repo
        run: git fetch second-repo
      - name: Merge repo
        run: git merge second-repo/main
      - name: Git push my repo
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "Cirrus CI"
          git push "https://MikuX-Dev:${{ secrets.PAT_TOKEN }}@github.com/MikuX-Dev/gpt4.git" main
