name: upload

on:  
  push:    
    branches:     
      - main
      
jobs:      
  build:         
    runs-on: ubuntu-latest

    steps:  
      - name: Checkout repository 
        uses: actions/checkout@v4
          
      - name: upload
        run: |
          mkdir iso
          cd iso
          wget https://cdimage.kali.org/kali-2023.4/kali-linux-2023.4-installer-purple-amd64.iso
          wget https://cdimage.kali.org/kali-2023.4/kali-linux-2023.4-installer-amd64.iso
          wget https://in-mirror.garudalinux.org/archlinux/iso/2024.01.01/archlinux-2024.01.01-x86_64.iso
          curl -p -T *.iso ftp://homeftp:123456789@10.27.27.1/usb1_1/isos/
