name: Compare Kernel

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  compare_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Replace 'x' with the desired version

      - name: Install dependencies
        run: pip install PyGithub pyTelegramBotAPI

      - name: Compare Kernel
        run: |
          python CI/compare_kernel.py

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v1.0.0  # Replace with the desired tag name
          release_name: Release v1.0.0  # Replace with the desired release name
          draft: false
          prerelease: false
          body: |
            This is the release body.

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Comparison Report
          path: CI/report.txt
