name: Push to Release

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  push_to_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Replace 'x' with the desired version

      - name: Install dependencies
        run: pip install PyGithub pyTelegramBotAPI

      - name: Run comparison script
        run: python CI/compare_kernel.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use your PAT secret name here
        with:
          tag_name: ${{ github.sha }}
          release_name: Release ${{ github.sha }}
          body: |
            This is an automated release triggered by the CI workflow.
          draft: false
          prerelease: false

      - name: Upload File to Release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}  # Use your PAT secret name here
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: CI/report.txt
          asset_name: report.txt
          asset_content_type: text/plain
