name: Compare Kernel

on:
  push:
    branches:
      - main

jobs:
  compare_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          repository: MikuX-Dev/CI
          ssh-strict: true
          persist-credentials: false
          clean: true
          fetch-depth: 1
          lfs: false
          submodules: false

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4

      - name: Install dependencies
        run: pip install PyGithub pyTelegramBotAPI

      - name: Compare Kernel
        run: |
          python compare_kernel.py

      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: v1.0.0
          release_name: Release v1.0.0
          draft: false
          prerelease: false
          body: |
            This is the release body.

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Comparison Report
          path: report.txt 
