name: Compare Kernel

on:
  push:
    branches:
      - main  # Adjust the branch name if needed

jobs:
  compare_kernel:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.11.4  # Replace 'x' with the desired version

      - name: Install dependencies
        run: pip install PyGithub pyTelegramBotAPI

      - name: Run comparison script
        run: |
          git clone https://github.com/MikuX-Dev/CI.git
          cd CI/.github/workflows
          python compare_kernel.py  # Replace with the actual filename of your script

      - name: Send report to Telegram
        run: |
          curl -F "chat_id=1780850118" -F "document=@${{ github.workspace }}/CI/report.txt" "https://api.telegram.org/bot6166928181:AAFddZ-KA7-_l6cPfFl7BRDL8Jb4fqmNy7M/sendDocument"
