name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up GitLab Runner
        run: |
          sudo apt-get install -y curl
          curl -LJO "https://gitlab-runner-downloads.s3.amazonaws.com/latest/deb/gitlab-runner_amd64.deb"
          sudo dpkg -i gitlab-runner_amd64.deb
          sudo gitlab-runner register --non-interactive --url https://gitlab.com/ --registration-token GR13489414shPz49gvaYaf8QNHsGU --executor "shell" --description "GitHub Runner" --tag-list "github-runner"

      - name: Start GitLab Runner
        run: |
           sudo gitlab-runner start
