name: GitHub to GitLab 

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          echo "${{ secrets.KNOWN_HOSTS }}" > ~/.ssh/known_hosts

      - name: Install unzip
        run: sudo apt-get install unzip -y

      - name: Download GitHub repositories
        run: |
          curl -L -o mikasa.zip https://github.com/Project-Mikasa/kernel_xiaomi_ysl/archive/refs/heads/mikasa.zip
          curl -L -o logon-ysl-common.zip https://github.com/Noob-214/Logan_Ysl/archive/refs/heads/common.zip
          curl -L -o logon-ysl-perf.zip https://github.com/Noob-214/Logan_Ysl/archive/refs/heads/perf.zip

      - name: Configure Git user
        run: |
          git config user.email "abinishanth3464@gmail.com"  # Replace with your email
          git config user.name "MikuX-Dev"  # Replace with your name

      - name: Unzip repositories
        run: |
          unzip mikasa.zip -d kernel_xiaomi_ysl-mikasa
          unzip logon-ysl-common.zip -d Logan_Ysl-common
          unzip logon-ysl-perf.zip -d Logan_Ysl-perf

      - name: Push mikasa branch to GitLab
        run: |
          cd kernel_xiaomi_ysl-mikasa/
          git init
          git remote add origin git@gitlab.com:bb-botos/local-manifest/kernel-xiaomi-ysl.git
          git checkout -b mikasa
          git add .
          git commit -m "Add mikasa branch"
          git push origin mikasa

      - name: Push logan-perf branch to GitLab
        run: |
          cd Logan_Ysl-perf/
          git init
          git remote add origin git@gitlab.com:bb-botos/local-manifest/kernel-xiaomi-ysl.git
          git checkout -b logan-perf
          git add .
          git commit -m "Add logan-perf branch"
          git push origin logan-perf

      - name: Push logan-common branch to GitLab
        run: |
          cd Logan_Ysl-common/
          git init
          git remote add origin git@gitlab.com:bb-botos/local-manifest/kernel-xiaomi-ysl.git
          git checkout -b logan-common
          git add .
          git commit -m "Add logan-common branch"
          git push origin logan-common
