name: GitHub to GitLab

on:
  push:
    branches:
      - mikasa

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Configure SSH
        run: |
          mkdir ~/.ssh/
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY_PUB }}" > ~/.ssh/id_rsa.pub
          chmod 600 ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa.pub
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Install Git LFS
        run: |
          sudo apt-get install git-lfs unzip -y
          git lfs install --skip-repo

      - name: Download GitHub repositories
        run: |
          curl -L -o mikasa.zip https://github.com/Project-Mikasa/kernel_xiaomi_ysl/archive/refs/heads/mikasa.zip
          # curl -L -o logon-ysl-common.zip https://github.com/Noob-214/Logan_Ysl/archive/refs/heads/common.zip
          # curl -L -o logon-ysl-perf.zip https://github.com/Noob-214/Logan_Ysl/archive/refs/heads/perf.zip

      - name: Unzip repositories
        run: |
          unzip mikasa.zip
          # unzip logon-ysl-common.zip
          # unzip logon-ysl-perf.zip

      - name: Push mikasa branch to GitLab
        run: |
          cd kernel_xiaomi_ysl-mikasa/
          git config user.email "abinishanth3464@gmail.com"
          git config user.name "MikuX-Dev"
          git lfs install --local
          git lfs track "*.c"
          git lfs track "*.h"
          git config lfs.https://gitlab.com/bb-botos/local-manifest/kernel-xiaomi-ysl.git/info/lfs.locksverify true
          git add -f .gitattributes
          git add .
          git commit -m "Add .gitattributes and mikasa branch"
          git remote add origin git@gitlab.com:bb-botos/local-manifest/kernel-xiaomi-ysl.git
          git push --set-upstream origin mikasa
